buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}



base {
    archivesName = "${mod_id}F-opts-dfc-mc${minecraft_version}-${mod_version}"
}



dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    api project(":harichunk_base")
    compileOnly project(":harichunk_quantified")
    compileOnly project(":harichunk_opts_gpu_noise")
}

processResources {
    var replaceProperties = [
            minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version       : forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id              : 'harichunk_opts_dfc', mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors         : mod_authors, mod_description: mod_description,
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
