org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -Djava.awt.headless=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47.,)
loader_version_range=[47.,)
mapping_channel=official
mapping_version=1.20.1
mod_id=harichunk
mod_name=HariChunk
mod_license=MIT, with some portions licensed under BRSSLA v1.5
mod_version=0.3.0
mod_group_id=com.hari.harichunk
mod_authors=HariMT, Admany
mod_description=Concurrent chunk management engine for faster chunk loading and processing. Powered by Quantified API.

# Java Dependencies
async_util_version=0.1.0
night_config_version=3.6.5
threadly_version=7.0
exp4j_version=0.4.8
mixinextras_version=0.5.4
mixin_tools_version=1.2.6

# FlowSched Dependencies
fastutil_version=8.5.12
rxjava_version=3.1.12
slf4j_version=2.0.9
