buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}



base {
    archivesName = "harichunk-harichunk_compat_immersivepetroleum-mc${minecraft_version}-${mod_version}"
}



dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    // Module dependencies
    api project(":harichunk_base")
    api project(":harichunk_opts_worldgen_general")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [minecraft_version: minecraft_version, minecraft_version_range: minecraft_version_range,
                             forge_version: forge_version, forge_version_range: forge_version_range,
                             loader_version_range: loader_version_range,
                             mod_id: "harichunk_compat_immersivepetroleum", mod_name: "HariChunk Compatibility/Immersive Petroleum", mod_license: mod_license, mod_version: mod_version,
                             mod_authors: mod_authors, mod_description: "Compatibility/Immersive Petroleum",]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}
